# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/destinelin/ROS/3d_generic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/destinelin/ROS/3d_generic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/destinelin/ROS/3d_generic/CMakeFiles /home/destinelin/ROS/3d_generic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/destinelin/ROS/3d_generic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_cpp

# Build rule for target.
ROSBUILD_genmsg_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_cpp
.PHONY : ROSBUILD_genmsg_cpp

# fast build rule for target.
ROSBUILD_genmsg_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_cpp.dir/build.make CMakeFiles/ROSBUILD_genmsg_cpp.dir/build
.PHONY : ROSBUILD_genmsg_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_lisp

# Build rule for target.
ROSBUILD_genmsg_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_lisp
.PHONY : ROSBUILD_genmsg_lisp

# fast build rule for target.
ROSBUILD_genmsg_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_lisp.dir/build.make CMakeFiles/ROSBUILD_genmsg_lisp.dir/build
.PHONY : ROSBUILD_genmsg_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_cpp

# Build rule for target.
ROSBUILD_gensrv_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_cpp
.PHONY : ROSBUILD_gensrv_cpp

# fast build rule for target.
ROSBUILD_gensrv_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_cpp.dir/build.make CMakeFiles/ROSBUILD_gensrv_cpp.dir/build
.PHONY : ROSBUILD_gensrv_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_lisp

# Build rule for target.
ROSBUILD_gensrv_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_lisp
.PHONY : ROSBUILD_gensrv_lisp

# fast build rule for target.
ROSBUILD_gensrv_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_lisp.dir/build.make CMakeFiles/ROSBUILD_gensrv_lisp.dir/build
.PHONY : ROSBUILD_gensrv_lisp/fast

#=============================================================================
# Target rules for targets named _catkin_empty_exported_target

# Build rule for target.
_catkin_empty_exported_target: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _catkin_empty_exported_target
.PHONY : _catkin_empty_exported_target

# fast build rule for target.
_catkin_empty_exported_target/fast:
	$(MAKE) -f CMakeFiles/_catkin_empty_exported_target.dir/build.make CMakeFiles/_catkin_empty_exported_target.dir/build
.PHONY : _catkin_empty_exported_target/fast

#=============================================================================
# Target rules for targets named binary_to_ply

# Build rule for target.
binary_to_ply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binary_to_ply
.PHONY : binary_to_ply

# fast build rule for target.
binary_to_ply/fast:
	$(MAKE) -f CMakeFiles/binary_to_ply.dir/build.make CMakeFiles/binary_to_ply.dir/build
.PHONY : binary_to_ply/fast

#=============================================================================
# Target rules for targets named clean_test_results

# Build rule for target.
clean_test_results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_test_results
.PHONY : clean_test_results

# fast build rule for target.
clean_test_results/fast:
	$(MAKE) -f CMakeFiles/clean_test_results.dir/build.make CMakeFiles/clean_test_results.dir/build
.PHONY : clean_test_results/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named extract_by_label

# Build rule for target.
extract_by_label: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract_by_label
.PHONY : extract_by_label

# fast build rule for target.
extract_by_label/fast:
	$(MAKE) -f CMakeFiles/extract_by_label.dir/build.make CMakeFiles/extract_by_label.dir/build
.PHONY : extract_by_label/fast

#=============================================================================
# Target rules for targets named rosbuild_clean-test-results

# Build rule for target.
rosbuild_clean-test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_clean-test-results
.PHONY : rosbuild_clean-test-results

# fast build rule for target.
rosbuild_clean-test-results/fast:
	$(MAKE) -f CMakeFiles/rosbuild_clean-test-results.dir/build.make CMakeFiles/rosbuild_clean-test-results.dir/build
.PHONY : rosbuild_clean-test-results/fast

#=============================================================================
# Target rules for targets named rosbuild_precompile

# Build rule for target.
rosbuild_precompile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_precompile
.PHONY : rosbuild_precompile

# fast build rule for target.
rosbuild_precompile/fast:
	$(MAKE) -f CMakeFiles/rosbuild_precompile.dir/build.make CMakeFiles/rosbuild_precompile.dir/build
.PHONY : rosbuild_precompile/fast

#=============================================================================
# Target rules for targets named rosbuild_premsgsrvgen

# Build rule for target.
rosbuild_premsgsrvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_premsgsrvgen
.PHONY : rosbuild_premsgsrvgen

# fast build rule for target.
rosbuild_premsgsrvgen/fast:
	$(MAKE) -f CMakeFiles/rosbuild_premsgsrvgen.dir/build.make CMakeFiles/rosbuild_premsgsrvgen.dir/build
.PHONY : rosbuild_premsgsrvgen/fast

#=============================================================================
# Target rules for targets named rospack_genmsg

# Build rule for target.
rospack_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg
.PHONY : rospack_genmsg

# fast build rule for target.
rospack_genmsg/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg.dir/build.make CMakeFiles/rospack_genmsg.dir/build
.PHONY : rospack_genmsg/fast

#=============================================================================
# Target rules for targets named rospack_genmsg_libexe

# Build rule for target.
rospack_genmsg_libexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg_libexe
.PHONY : rospack_genmsg_libexe

# fast build rule for target.
rospack_genmsg_libexe/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg_libexe.dir/build.make CMakeFiles/rospack_genmsg_libexe.dir/build
.PHONY : rospack_genmsg_libexe/fast

#=============================================================================
# Target rules for targets named rospack_gensrv

# Build rule for target.
rospack_gensrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv
.PHONY : rospack_gensrv

# fast build rule for target.
rospack_gensrv/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv.dir/build.make CMakeFiles/rospack_gensrv.dir/build
.PHONY : rospack_gensrv/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-future

# Build rule for target.
test-future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-future
.PHONY : test-future

# fast build rule for target.
test-future/fast:
	$(MAKE) -f CMakeFiles/test-future.dir/build.make CMakeFiles/test-future.dir/build
.PHONY : test-future/fast

#=============================================================================
# Target rules for targets named test-results

# Build rule for target.
test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results
.PHONY : test-results

# fast build rule for target.
test-results/fast:
	$(MAKE) -f CMakeFiles/test-results.dir/build.make CMakeFiles/test-results.dir/build
.PHONY : test-results/fast

#=============================================================================
# Target rules for targets named test-results-run

# Build rule for target.
test-results-run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results-run
.PHONY : test-results-run

# fast build rule for target.
test-results-run/fast:
	$(MAKE) -f CMakeFiles/test-results-run.dir/build.make CMakeFiles/test-results-run.dir/build
.PHONY : test-results-run/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named to_ascii

# Build rule for target.
to_ascii: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 to_ascii
.PHONY : to_ascii

# fast build rule for target.
to_ascii/fast:
	$(MAKE) -f CMakeFiles/to_ascii.dir/build.make CMakeFiles/to_ascii.dir/build
.PHONY : to_ascii/fast

#=============================================================================
# Target rules for targets named to_binary

# Build rule for target.
to_binary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 to_binary
.PHONY : to_binary

# fast build rule for target.
to_binary/fast:
	$(MAKE) -f CMakeFiles/to_binary.dir/build.make CMakeFiles/to_binary.dir/build
.PHONY : to_binary/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest.dir/build.make gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest_main.dir/build.make gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/binary_to_ply.o: src/binary_to_ply.cpp.o
.PHONY : src/binary_to_ply.o

# target to build an object file
src/binary_to_ply.cpp.o:
	$(MAKE) -f CMakeFiles/binary_to_ply.dir/build.make CMakeFiles/binary_to_ply.dir/src/binary_to_ply.cpp.o
.PHONY : src/binary_to_ply.cpp.o

src/binary_to_ply.i: src/binary_to_ply.cpp.i
.PHONY : src/binary_to_ply.i

# target to preprocess a source file
src/binary_to_ply.cpp.i:
	$(MAKE) -f CMakeFiles/binary_to_ply.dir/build.make CMakeFiles/binary_to_ply.dir/src/binary_to_ply.cpp.i
.PHONY : src/binary_to_ply.cpp.i

src/binary_to_ply.s: src/binary_to_ply.cpp.s
.PHONY : src/binary_to_ply.s

# target to generate assembly for a file
src/binary_to_ply.cpp.s:
	$(MAKE) -f CMakeFiles/binary_to_ply.dir/build.make CMakeFiles/binary_to_ply.dir/src/binary_to_ply.cpp.s
.PHONY : src/binary_to_ply.cpp.s

src/convert.o: src/convert.cpp.o
.PHONY : src/convert.o

# target to build an object file
src/convert.cpp.o:
	$(MAKE) -f CMakeFiles/to_binary.dir/build.make CMakeFiles/to_binary.dir/src/convert.cpp.o
.PHONY : src/convert.cpp.o

src/convert.i: src/convert.cpp.i
.PHONY : src/convert.i

# target to preprocess a source file
src/convert.cpp.i:
	$(MAKE) -f CMakeFiles/to_binary.dir/build.make CMakeFiles/to_binary.dir/src/convert.cpp.i
.PHONY : src/convert.cpp.i

src/convert.s: src/convert.cpp.s
.PHONY : src/convert.s

# target to generate assembly for a file
src/convert.cpp.s:
	$(MAKE) -f CMakeFiles/to_binary.dir/build.make CMakeFiles/to_binary.dir/src/convert.cpp.s
.PHONY : src/convert.cpp.s

src/extract_by_label.o: src/extract_by_label.cpp.o
.PHONY : src/extract_by_label.o

# target to build an object file
src/extract_by_label.cpp.o:
	$(MAKE) -f CMakeFiles/extract_by_label.dir/build.make CMakeFiles/extract_by_label.dir/src/extract_by_label.cpp.o
.PHONY : src/extract_by_label.cpp.o

src/extract_by_label.i: src/extract_by_label.cpp.i
.PHONY : src/extract_by_label.i

# target to preprocess a source file
src/extract_by_label.cpp.i:
	$(MAKE) -f CMakeFiles/extract_by_label.dir/build.make CMakeFiles/extract_by_label.dir/src/extract_by_label.cpp.i
.PHONY : src/extract_by_label.cpp.i

src/extract_by_label.s: src/extract_by_label.cpp.s
.PHONY : src/extract_by_label.s

# target to generate assembly for a file
src/extract_by_label.cpp.s:
	$(MAKE) -f CMakeFiles/extract_by_label.dir/build.make CMakeFiles/extract_by_label.dir/src/extract_by_label.cpp.s
.PHONY : src/extract_by_label.cpp.s

src/to_ascii.o: src/to_ascii.cpp.o
.PHONY : src/to_ascii.o

# target to build an object file
src/to_ascii.cpp.o:
	$(MAKE) -f CMakeFiles/to_ascii.dir/build.make CMakeFiles/to_ascii.dir/src/to_ascii.cpp.o
.PHONY : src/to_ascii.cpp.o

src/to_ascii.i: src/to_ascii.cpp.i
.PHONY : src/to_ascii.i

# target to preprocess a source file
src/to_ascii.cpp.i:
	$(MAKE) -f CMakeFiles/to_ascii.dir/build.make CMakeFiles/to_ascii.dir/src/to_ascii.cpp.i
.PHONY : src/to_ascii.cpp.i

src/to_ascii.s: src/to_ascii.cpp.s
.PHONY : src/to_ascii.s

# target to generate assembly for a file
src/to_ascii.cpp.s:
	$(MAKE) -f CMakeFiles/to_ascii.dir/build.make CMakeFiles/to_ascii.dir/src/to_ascii.cpp.s
.PHONY : src/to_ascii.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ROSBUILD_genmsg_cpp"
	@echo "... ROSBUILD_genmsg_lisp"
	@echo "... ROSBUILD_gensrv_cpp"
	@echo "... ROSBUILD_gensrv_lisp"
	@echo "... _catkin_empty_exported_target"
	@echo "... binary_to_ply"
	@echo "... clean_test_results"
	@echo "... doxygen"
	@echo "... edit_cache"
	@echo "... extract_by_label"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... rosbuild_clean-test-results"
	@echo "... rosbuild_precompile"
	@echo "... rosbuild_premsgsrvgen"
	@echo "... rospack_genmsg"
	@echo "... rospack_genmsg_libexe"
	@echo "... rospack_gensrv"
	@echo "... run_tests"
	@echo "... test"
	@echo "... test-future"
	@echo "... test-results"
	@echo "... test-results-run"
	@echo "... tests"
	@echo "... to_ascii"
	@echo "... to_binary"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/binary_to_ply.o"
	@echo "... src/binary_to_ply.i"
	@echo "... src/binary_to_ply.s"
	@echo "... src/convert.o"
	@echo "... src/convert.i"
	@echo "... src/convert.s"
	@echo "... src/extract_by_label.o"
	@echo "... src/extract_by_label.i"
	@echo "... src/extract_by_label.s"
	@echo "... src/to_ascii.o"
	@echo "... src/to_ascii.i"
	@echo "... src/to_ascii.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

